### ISSUE TITLE
Stop logging to the dev console for the release extension (or provide an option to disable it)

### ISSUE THREAD

**Issue by shauser** [limpkin/mooltipass#175]
I understand that debug logging is necessary for extension developers but version 1.1.13 of the extension makes working as a web developer basically impossible. We get a `check_for_new_input_fields` every second now and can barely find our own messages in between all the unrelated messages.

Also, if I put localhost on the blacklist, the logging is NOT disabled, which it should be.

**Comment by lukasgeiter** [comment]
:+1:

**Comment by limpkin** [comment]
pushed and solved in latest commit, (.14 version), can you update and check?

**Comment by shauser** [comment]
The excessive debug logs are gone (thanks for the VERY fast fix - 11 minutes from creation to push), but the other messages (`console.log(cip.settings.status);` and `console.log('initCredentialFields():', inputs.length, 'input fields found');`) are still shown.

**Comment by limpkin** [comment]
everything should be silent with .15 now ;)

**Comment by yankee42** [comment]
I still get a lot of log output in Firefox with Version 1.3.4:

![image](https://user-images.githubusercontent.com/1841729/31169965-ad69d1ee-a8fa-11e7-97c6-03c08c2e79ab.png)

Am I doing something wrong or is this a regression?

**Comment by limpkin** [comment]
@reepush: could you check that test?

https://github.com/limpkin/mooltipass/blob/master/chrome_extension/mooltipass-content.js#L18

**Comment by limpkin** [comment]
@reepush: it seems it was changed by you:
https://github.com/limpkin/mooltipass/commit/c121a0a58e33f3513ebee4d61876c07b764276af#diff-33e5fa0d6722e4478e22e1aa6b1424e4L18

**Comment by reepush** [comment]
@limpkin [filed pr with a fix](https://github.com/limpkin/mooltipass/pull/505)
